source: site
paths:
  uploads: uploads
  static: ''
collections_config:
  data:
    path: _data
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: collections/_posts
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    _enabled_editors:
      - visual
      - content
    schemas:
      default:
        path: site/schemas/post.md
  pages:
    path: collections/_pages
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/page.html
  projects:
    path: collections/_projects
    icon: work_outline
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/project.md
  testimonials:
    path: collections/_testimonials
    disable_url: false
    icon: format_quote
    sort:
      key: name
    sort_options:
      - key: name
      - key: name
        order: desc
      - key: position
      - key: position
        order: desc
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: site/schemas/testimonial.md
  drafts:
    path: collections/_drafts
    create:
      publish_to: posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
collection_groups:
  - heading: Content
    collections:
      - pages
      - projects
      - testimonials
  - heading: Blogging
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data
_inputs:
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  
timezone: Etc/UTC

_snippets:
  image:
    snippet: '{% include snippets/image.html [[arguments]] %}'
    params:
      arguments:
        parser: key_values
        options:
          models:
            - editor_key: url
            - editor_key: max-width
            - editor_key: file
            - editor_key: alt
            - editor_key: caption
          format:
            string_boundary:
              - '"'
            root_value_delimiter: '='
    _inputs:
      caption:
        type: textarea
      file:
        type: image
